<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'sub_category' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ) ),
'fields' => array( 'gridFields' => array( 'status',
'now',
'updated',
'title' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'status' => array( 'integrated_edit_field24',
'integrated_edit_field7',
'integrated_edit_field25' ),
'now' => array( 'integrated_edit_field26',
'integrated_edit_field8',
'integrated_edit_field27' ),
'updated' => array( 'integrated_edit_field28',
'integrated_edit_field9',
'integrated_edit_field29' ),
'title' => array( 'edit_field',
'edit_field_label',
'edit_field_tooltip' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'grid' => array( 'edit_field_label',
'edit_field',
'edit_field_tooltip',
'integrated_edit_field24',
'integrated_edit_field7',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field8',
'integrated_edit_field27',
'master_info',
'integrated_edit_field28',
'integrated_edit_field9',
'integrated_edit_field29',
'details_preview' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'edit_field_label' => 'grid',
'edit_field' => 'grid',
'edit_field_tooltip' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field27' => 'grid',
'master_info' => 'grid',
'integrated_edit_field28' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field29' => 'grid',
'details_preview' => 'grid' ),
'itemLocations' => array( 'edit_field_label' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'edit_field' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'edit_field_tooltip' => array( 'location' => 'grid',
'cellId' => 'c24' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c25' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c26' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c27' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c28' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c29' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c30' ),
'master_info' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_edit_field28' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'integrated_edit_field29' => array( 'location' => 'grid',
'cellId' => 'c' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'edit_field_label' => array( 'integrated_edit_field24',
'integrated_edit_field26',
'integrated_edit_field28',
'edit_field_label' ),
'edit_field' => array( 'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'edit_field' ),
'edit_field_tooltip' => array( 'integrated_edit_field25',
'integrated_edit_field27',
'integrated_edit_field29',
'edit_field_tooltip' ),
'master_info' => array( 'master_info' ),
'details_preview' => array( 'details_preview' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'master_info' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'title_fieldblock' ),
'items' => array( 'edit_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'edit_field_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'status_fieldblock' ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'now_fieldblock' ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c29' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c30' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'updated_fieldblock' ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 6 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 3 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c22' ),
array( 'cell' => 'c23' ),
array( 'cell' => 'c24' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c25' ),
array( 'cell' => 'c26' ),
array( 'cell' => 'c27' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c28' ),
array( 'cell' => 'c29' ),
array( 'cell' => 'c30' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 3 ) ),
'section' => '' ) ),
'cells' => array( 'c22' => array( 'model' => 'c4',
'items' => array( 'edit_field_label' ),
'field' => 'status' ),
'c23' => array( 'model' => 'c2',
'items' => array( 'edit_field' ),
'field' => 'status' ),
'c24' => array( 'model' => 'c2',
'items' => array( 'edit_field_tooltip' ),
'field' => 'status' ),
'c25' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field24' ),
'field' => 'now' ),
'c26' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field7' ),
'field' => 'now' ),
'c27' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field25' ),
'field' => 'now' ),
'c28' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field26' ),
'field' => 'updated' ),
'c29' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field8' ),
'field' => 'updated' ),
'c30' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field27' ),
'field' => 'updated' ),
'c1' => array( 'model' => 'c1',
'items' => array( 'master_info' ),
'field' => null ),
'c4' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field28' ),
'field' => 'title' ),
'c2' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field9' ),
'field' => 'title' ),
'c' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field29' ),
'field' => 'title' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'details_preview' ),
'field' => null ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => true,
'separateLabels' => true ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field24' => array( 'type' => 'edit_field_label',
'field' => 'status' ),
'integrated_edit_field7' => array( 'field' => 'status',
'type' => 'edit_field' ),
'integrated_edit_field25' => array( 'type' => 'edit_field_tooltip',
'field' => 'status' ),
'integrated_edit_field26' => array( 'type' => 'edit_field_label',
'field' => 'now' ),
'integrated_edit_field8' => array( 'field' => 'now',
'type' => 'edit_field' ),
'integrated_edit_field27' => array( 'type' => 'edit_field_tooltip',
'field' => 'now' ),
'integrated_edit_field28' => array( 'type' => 'edit_field_label',
'field' => 'updated' ),
'integrated_edit_field9' => array( 'field' => 'updated',
'type' => 'edit_field' ),
'integrated_edit_field29' => array( 'type' => 'edit_field_tooltip',
'field' => 'updated' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'sub_category' => 'true' ) ),
'edit_field' => array( 'field' => 'title',
'type' => 'edit_field' ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'title' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'sub_category',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'title' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>