<?php
			$optionsArray = array( 'details' => array( 'sub_category' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'question_name',
'category',
'question_ans_1',
'question_ans_2',
'question_ans_3',
'question_ans_4',
'question_correct_ans',
'status',
'now',
'updated' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'question_name' => array( 'integrated_edit_field',
'integrated_edit_field10',
'integrated_edit_field11' ),
'category' => array( 'integrated_edit_field1',
'integrated_edit_field12',
'integrated_edit_field13' ),
'question_ans_1' => array( 'integrated_edit_field2',
'integrated_edit_field14',
'integrated_edit_field15' ),
'question_ans_2' => array( 'integrated_edit_field3',
'integrated_edit_field16',
'integrated_edit_field17' ),
'question_ans_3' => array( 'integrated_edit_field4',
'integrated_edit_field18',
'integrated_edit_field19' ),
'question_ans_4' => array( 'integrated_edit_field5',
'integrated_edit_field20',
'integrated_edit_field21' ),
'question_correct_ans' => array( 'integrated_edit_field6',
'integrated_edit_field22',
'integrated_edit_field23' ),
'status' => array( 'integrated_edit_field7',
'integrated_edit_field24',
'integrated_edit_field25' ),
'now' => array( 'integrated_edit_field8',
'integrated_edit_field26',
'integrated_edit_field27' ),
'updated' => array( 'integrated_edit_field9',
'integrated_edit_field28',
'integrated_edit_field29' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'collapse_button',
'breadcrumb',
'loginform_login',
'username_button' ),
'left' => array( 'logo1',
'expand_button',
'menu' ),
'top' => array( 'add_header' ),
'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'integrated_edit_field10',
'integrated_edit_field',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field1',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field2',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field3',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field4',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field5',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field6',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field7',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field8',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field9',
'integrated_edit_field29' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'add_header' => 'top',
'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field13' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field27' => 'grid',
'integrated_edit_field28' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field29' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c15' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c16' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c17' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c19' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c20' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c21' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c24' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c25' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c26' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c27' ),
'integrated_edit_field28' => array( 'location' => 'grid',
'cellId' => 'c28' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c29' ),
'integrated_edit_field29' => array( 'location' => 'grid',
'cellId' => 'c30' ) ),
'itemVisiblity' => array( 'collapse_button' => 5,
'loginform_login' => 3,
'username_button' => 3,
'expand_button' => 5,
'menu' => 3 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'loginform_login' => array( 'loginform_login' ),
'username_button' => array( 'username_button' ),
'logout_link' => array( 'logout_link' ),
'collapse_button' => array( 'collapse_button' ),
'edit_field_label' => array( 'integrated_edit_field10',
'integrated_edit_field12',
'integrated_edit_field14',
'integrated_edit_field16',
'integrated_edit_field18',
'integrated_edit_field20',
'integrated_edit_field22',
'integrated_edit_field24',
'integrated_edit_field26',
'integrated_edit_field28' ),
'edit_field_tooltip' => array( 'integrated_edit_field11',
'integrated_edit_field13',
'integrated_edit_field15',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field21',
'integrated_edit_field23',
'integrated_edit_field25',
'integrated_edit_field27',
'integrated_edit_field29' ),
'logo' => array( 'logo1' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'question_name_fieldblock' ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'category_fieldblock' ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'question_ans_1_fieldblock' ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'question_ans_2_fieldblock' ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'question_ans_3_fieldblock' ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'question_ans_4_fieldblock' ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'question_correct_ans_fieldblock' ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'status_fieldblock' ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'now_fieldblock' ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'updated_fieldblock' ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c29' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c30' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 10 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'add',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c5' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c6' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ),
array( 'cell' => 'c15' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c16' ),
array( 'cell' => 'c17' ),
array( 'cell' => 'c18' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c19' ),
array( 'cell' => 'c20' ),
array( 'cell' => 'c21' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c22' ),
array( 'cell' => 'c23' ),
array( 'cell' => 'c24' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c25' ),
array( 'cell' => 'c26' ),
array( 'cell' => 'c27' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c28' ),
array( 'cell' => 'c29' ),
array( 'cell' => 'c30' ) ),
'section' => '' ) ),
'cells' => array( 'c4' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field10' ),
'field' => 'question_name' ),
'c2' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field' ),
'field' => 'question_name' ),
'c' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field11' ),
'field' => 'question_name' ),
'c5' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field12' ),
'field' => 'category' ),
'c3' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field1' ),
'field' => 'category' ),
'c6' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field13' ),
'field' => 'category' ),
'c7' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field14' ),
'field' => 'question_ans_1' ),
'c8' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field2' ),
'field' => 'question_ans_1' ),
'c9' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field15' ),
'field' => 'question_ans_1' ),
'c10' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field16' ),
'field' => 'question_ans_2' ),
'c11' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field3' ),
'field' => 'question_ans_2' ),
'c12' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field17' ),
'field' => 'question_ans_2' ),
'c13' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field18' ),
'field' => 'question_ans_3' ),
'c14' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field4' ),
'field' => 'question_ans_3' ),
'c15' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field19' ),
'field' => 'question_ans_3' ),
'c16' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field20' ),
'field' => 'question_ans_4' ),
'c17' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field5' ),
'field' => 'question_ans_4' ),
'c18' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field21' ),
'field' => 'question_ans_4' ),
'c19' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field22' ),
'field' => 'question_correct_ans' ),
'c20' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field6' ),
'field' => 'question_correct_ans' ),
'c21' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field23' ),
'field' => 'question_correct_ans' ),
'c22' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field24' ),
'field' => 'status' ),
'c23' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field7' ),
'field' => 'status' ),
'c24' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field25' ),
'field' => 'status' ),
'c25' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field26' ),
'field' => 'now' ),
'c26' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field8' ),
'field' => 'now' ),
'c27' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field27' ),
'field' => 'now' ),
'c28' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field28' ),
'field' => 'updated' ),
'c29' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field9' ),
'field' => 'updated' ),
'c30' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field29' ),
'field' => 'updated' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => true,
'separateLabels' => true ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'integrated_edit_field' => array( 'field' => 'question_name',
'type' => 'edit_field' ),
'integrated_edit_field1' => array( 'field' => 'category',
'type' => 'edit_field' ),
'integrated_edit_field2' => array( 'field' => 'question_ans_1',
'type' => 'edit_field' ),
'integrated_edit_field3' => array( 'field' => 'question_ans_2',
'type' => 'edit_field' ),
'integrated_edit_field4' => array( 'field' => 'question_ans_3',
'type' => 'edit_field' ),
'integrated_edit_field5' => array( 'field' => 'question_ans_4',
'type' => 'edit_field' ),
'integrated_edit_field6' => array( 'field' => 'question_correct_ans',
'type' => 'edit_field' ),
'integrated_edit_field7' => array( 'field' => 'status',
'type' => 'edit_field' ),
'integrated_edit_field8' => array( 'field' => 'now',
'type' => 'edit_field' ),
'integrated_edit_field9' => array( 'field' => 'updated',
'type' => 'edit_field' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'loginform_login' => array( 'type' => 'loginform_login' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link' ) ),
'logout_link' => array( 'type' => 'logout_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'integrated_edit_field10' => array( 'type' => 'edit_field_label',
'field' => 'question_name' ),
'integrated_edit_field11' => array( 'type' => 'edit_field_tooltip',
'field' => 'question_name' ),
'integrated_edit_field12' => array( 'type' => 'edit_field_label',
'field' => 'category' ),
'integrated_edit_field13' => array( 'type' => 'edit_field_tooltip',
'field' => 'category' ),
'integrated_edit_field14' => array( 'type' => 'edit_field_label',
'field' => 'question_ans_1' ),
'integrated_edit_field15' => array( 'type' => 'edit_field_tooltip',
'field' => 'question_ans_1' ),
'integrated_edit_field16' => array( 'type' => 'edit_field_label',
'field' => 'question_ans_2' ),
'integrated_edit_field17' => array( 'type' => 'edit_field_tooltip',
'field' => 'question_ans_2' ),
'integrated_edit_field18' => array( 'type' => 'edit_field_label',
'field' => 'question_ans_3' ),
'integrated_edit_field19' => array( 'type' => 'edit_field_tooltip',
'field' => 'question_ans_3' ),
'integrated_edit_field20' => array( 'type' => 'edit_field_label',
'field' => 'question_ans_4' ),
'integrated_edit_field21' => array( 'type' => 'edit_field_tooltip',
'field' => 'question_ans_4' ),
'integrated_edit_field22' => array( 'type' => 'edit_field_label',
'field' => 'question_correct_ans' ),
'integrated_edit_field23' => array( 'type' => 'edit_field_tooltip',
'field' => 'question_correct_ans' ),
'integrated_edit_field24' => array( 'type' => 'edit_field_label',
'field' => 'status' ),
'integrated_edit_field25' => array( 'type' => 'edit_field_tooltip',
'field' => 'status' ),
'integrated_edit_field26' => array( 'type' => 'edit_field_label',
'field' => 'now' ),
'integrated_edit_field27' => array( 'type' => 'edit_field_tooltip',
'field' => 'now' ),
'integrated_edit_field28' => array( 'type' => 'edit_field_label',
'field' => 'updated' ),
'integrated_edit_field29' => array( 'type' => 'edit_field_tooltip',
'field' => 'updated' ),
'logo1' => array( 'type' => 'logo' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>