<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'status',
'now',
'updated' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'status' => array( 'integrated_edit_field7',
'integrated_edit_field24',
'integrated_edit_field25' ),
'now' => array( 'integrated_edit_field8',
'integrated_edit_field26',
'integrated_edit_field27' ),
'updated' => array( 'integrated_edit_field28',
'integrated_edit_field9',
'integrated_edit_field29' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'integrated_edit_field24',
'integrated_edit_field7',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field8',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field9',
'integrated_edit_field29' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field27' => 'grid',
'integrated_edit_field28' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field29' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c24' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c25' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c26' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c27' ),
'integrated_edit_field28' => array( 'location' => 'grid',
'cellId' => 'c28' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c29' ),
'integrated_edit_field29' => array( 'location' => 'grid',
'cellId' => 'c30' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'edit_view' => array( 'edit_view' ),
'edit_field' => array( 'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9' ),
'edit_field_label' => array( 'integrated_edit_field24',
'integrated_edit_field26',
'integrated_edit_field28' ),
'edit_field_tooltip' => array( 'integrated_edit_field25',
'integrated_edit_field27',
'integrated_edit_field29' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c22' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'status_fieldblock' ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'now_fieldblock' ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'updated_fieldblock' ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c29' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c30' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c22' ),
array( 'cell' => 'c23' ),
array( 'cell' => 'c24' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c25' ),
array( 'cell' => 'c26' ),
array( 'cell' => 'c27' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c28' ),
array( 'cell' => 'c29' ),
array( 'cell' => 'c30' ) ),
'section' => '' ) ),
'cells' => array( 'c22' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field24' ),
'field' => 'status' ),
'c23' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field7' ),
'field' => 'status' ),
'c24' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field25' ),
'field' => 'status' ),
'c25' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field26' ),
'field' => 'now' ),
'c26' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field8' ),
'field' => 'now' ),
'c27' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field27' ),
'field' => 'now' ),
'c28' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field28' ),
'field' => 'updated' ),
'c29' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field9' ),
'field' => 'updated' ),
'c30' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field29' ),
'field' => 'updated' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => true,
'separateLabels' => true ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field7' => array( 'field' => 'status',
'type' => 'edit_field' ),
'integrated_edit_field8' => array( 'field' => 'now',
'type' => 'edit_field',
'updateOnEdit' => false ),
'integrated_edit_field24' => array( 'type' => 'edit_field_label',
'field' => 'status' ),
'integrated_edit_field25' => array( 'type' => 'edit_field_tooltip',
'field' => 'status' ),
'integrated_edit_field26' => array( 'type' => 'edit_field_label',
'field' => 'now' ),
'integrated_edit_field27' => array( 'type' => 'edit_field_tooltip',
'field' => 'now' ),
'integrated_edit_field28' => array( 'type' => 'edit_field_label',
'field' => 'updated' ),
'integrated_edit_field9' => array( 'field' => 'updated',
'type' => 'edit_field',
'updateOnEdit' => false ),
'integrated_edit_field29' => array( 'type' => 'edit_field_tooltip',
'field' => 'updated' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>